<?php
/**
 * @file
 * Module to embed views using tokens
 */

/**
 * Implements hook_token_info().
 */
function token_embed_views_token_info() {
  $info['types']['views'] = array(
    'name' => t('Views'),
    'description' => ('Tokens to embed views.'),
  );
  $info['tokens']['views']['embed'] = array(
    'name' => t('Embed views'),
    'description' => t('Embed views using tokens. The following values may be appended to the token: view-name:display-id:arg1/arg2/arg3'),
    'dynamic' => TRUE,
  );
  return $info;
}

/**
 * Implements hook_tokens().
 */
function token_embed_views_tokens($type, $tokens, array $data = array(), array $options = array()) {
  if ($type == 'views') {
    $replacements = array();
    foreach ($tokens as $token => $key) {
      // Extract info.
      $args = explode(':', $token);
      $token_name = array_shift($args);
      $view_name  = array_shift($args);
      $display_id = array_shift($args);

      // Fetch the view.
      $replacements[$key] = views_embed_view($view_name, $display_id, $args);
    }
    return $replacements;
  }
}
