<?php
/**
 * @file
 * Module to embed views using tokens
 */

/**
 * Implements hook_token_info().
 */
function token_embed_views_token_info() {
  $info['tokens']['site']['views-embed'] = array(
    'name' => t('Embed views'),
    'description' => t('Embed views using tokens. The following values may be appended to the token: view-name:display-id:arg1/arg2/arg3'),
    'dynamic' => TRUE,
  );
  return $info;
}

/**
 * Implements hook_tokens().
 */
function token_embed_views_tokens($type, $tokens, array $data = array(), array $options = array()) {
  if ($type == 'site') {dpm($tokens);
    if($views_infos = token_find_with_prefix($tokens, 'views-embed')) {
      foreach ($views_infos as $views_info => $original) {
        $args = explode(':', $views_info);
        // Fetch the view with all args passed to it.
        $view = views_get_view($args[0]);
        if (!empty($view)) {
          $replacements[$original] = call_user_func_array('views_embed_view', $args);
        }
      }
    }
    return $replacements;
  }
}
